#!/bin/bash
# User Data script template for EC2 instances
# Variables are injected by Terraform templatefile() function
# This script installs NGINX as reverse proxy and deploys 5 users microservices

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

LOG_FILE="/var/log/user_data.log"
exec > >(tee -a $LOG_FILE)
exec 2>&1

echo "=== User Data Script Started ==="
echo "Timestamp: $(date)"

# Install Docker and NGINX
apt-get update -y
apt-get install -y docker.io curl jq nginx

systemctl enable docker
systemctl start docker

systemctl enable nginx
# Don't start NGINX yet - we'll start it after containers are ready

# Allow docker without sudo
usermod -aG docker ubuntu

echo "Docker installed: $(docker --version)"
echo "NGINX installed: $(nginx -v 2>&1)"

# Docker Hub login if credentials provided
if [ -n "${dockerhub_username}" ] && [ -n "${dockerhub_token}" ]; then
  echo "${dockerhub_token}" | docker login -u "${dockerhub_username}" --password-stdin || true
  echo "Docker Hub login completed"
fi

# Create .env file with Terraform variables
cat > /home/ubuntu/.env <<ENVFILE
# Database Configuration
DB_HOST=${db_host}
DB_USER=${db_user}
DB_PASSWORD=${db_password}
DB_NAME=${db_name}
DB_PORT=${db_port}

# Service Configuration
NODE_ENV=production

# API Gateway URL (use Load Balancer DNS - API Gateway is in another account)
API_GATEWAY_URL=http://${loadbalancer_dns}

# Service URLs (use Load Balancer DNS for all services)
USERS_CREATE_URL=http://${loadbalancer_dns}
USERS_DELETE_URL=http://${loadbalancer_dns}
USERS_LIST_URL=http://${loadbalancer_dns}
USERS_SEARCH_URL=http://${loadbalancer_dns}
USERS_UPDATE_URL=http://${loadbalancer_dns}
AUTH_LOGIN_URL=http://${loadbalancer_dns}
AUTH_ROL_URL=http://${loadbalancer_dns}
AUTH_ME_URL=http://${loadbalancer_dns}
FILE_SERVICE_INIT_URL=http://${loadbalancer_dns}
FILE_SERVICE_UPDATE_URL=http://${loadbalancer_dns}
FILE_SERVICE_UPLOAD_URL=http://${loadbalancer_dns}
FILE_SERVICE_LIST_URL=http://${loadbalancer_dns}
FILE_SERVICE_DOWNLOAD_URL=http://${loadbalancer_dns}

# JWT Configuration
JWT_SECRET=${jwt_secret}
JWT_EXPIRES_IN=24h
ENVFILE

chown ubuntu:ubuntu /home/ubuntu/.env
chmod 600 /home/ubuntu/.env

echo ".env file created at /home/ubuntu/.env"
echo "Load Balancer DNS: ${loadbalancer_dns}"

# Create NGINX configuration
cat > /etc/nginx/conf.d/users.conf <<'NGINXCONF'
# NGINX Configuration for GradFlow Users Services
# This file is generated by user-data-template.sh

# Upstream definitions for backend services
upstream users_create {
    server 127.0.0.1:3001;
}

upstream users_delete {
    server 127.0.0.1:3002;
}

upstream users_list {
    server 127.0.0.1:3003;
}

upstream users_search {
    server 127.0.0.1:3004;
}

upstream users_update {
    server 127.0.0.1:3005;
}

# Main server block
server {
    listen 80;
    server_name _;

    # Increase timeouts for long-running requests
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;

    # Buffer settings
    proxy_buffering on;
    proxy_buffer_size 4k;
    proxy_buffers 8 4k;
    proxy_busy_buffers_size 8k;

    # Headers for proper proxy behavior
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;

    # Route /api/users/create to users-create service
    location /api/users/create {
        proxy_pass http://users_create/api/users;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # Route /api/users/delete to users-delete service
    location ~ ^/api/users/([^/]+)/delete$ {
        proxy_pass http://users_delete/api/users/$1;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # Route /api/users (list) to users-list service
    location /api/users {
        proxy_pass http://users_list/api/users;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # Route /api/users/search to users-search service
    location /api/users/search {
        proxy_pass http://users_search/api/users/search;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # Route /api/users/update to users-update service
    location ~ ^/api/users/([^/]+)/update$ {
        proxy_pass http://users_update/api/users/$1;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # Health check endpoint for ALB
    location / {
        return 200 "OK";
        add_header Content-Type text/plain;
    }

    # Error pages
    error_page 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
NGINXCONF

chmod 644 /etc/nginx/conf.d/users.conf

# Remove default NGINX site
rm -f /etc/nginx/sites-enabled/default

# Test NGINX configuration
nginx -t || {
  echo "ERROR: NGINX configuration test failed"
  exit 1
}

echo "NGINX configuration created and validated"

# Function to stop and remove existing container
stop_and_remove_container() {
  local container_name=$1
  docker stop "$container_name" 2>/dev/null || true
  docker rm "$container_name" 2>/dev/null || true
}

# Function to pull and run container
deploy_container() {
  local container_name=$1
  local image_name=$2
  local port=$3
  local env_file="/home/ubuntu/.env"

  echo "Deploying $container_name..."

  # Stop and remove existing container
  stop_and_remove_container "$container_name"

  # Pull Docker image
  if [ -n "$image_name" ]; then
    echo "Pulling Docker image: $image_name"
    docker pull "$image_name" || {
      echo "Warning: Failed to pull image $image_name"
      return 1
    }
  else
    echo "Warning: No image specified for $container_name, skipping"
    return 1
  fi

  # Run container
  docker run -d \
    --name "$container_name" \
    --restart always \
    -p 0.0.0.0:$port:$port \
    --env-file "$env_file" \
    "$image_name" || {
      echo "Warning: Failed to start container $container_name"
      return 1
    }

  echo "Container $container_name started on port $port (localhost only)"
  docker ps --filter "name=$container_name" --format "{{.Names}}: {{.Status}}"
}

# Deploy all 5 users containers
deploy_container "users-create" "${docker_image_users_create}" 3001 || true
deploy_container "users-delete" "${docker_image_users_delete}" 3002 || true
deploy_container "users-list" "${docker_image_users_list}" 3003 || true
deploy_container "users-search" "${docker_image_users_search}" 3004 || true
deploy_container "users-update" "${docker_image_users_update}" 3005 || true

# Wait a few seconds for containers to be ready
echo "Waiting for containers to initialize..."
sleep 10

# Verify containers are running
echo "Container status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

# Start NGINX (after containers are deployed)
echo "Starting NGINX..."
systemctl start nginx
systemctl status nginx --no-pager || echo "Warning: NGINX may not have started correctly"

# Verify NGINX is running
if systemctl is-active --quiet nginx; then
  echo "NGINX is running successfully"
else
  echo "ERROR: NGINX failed to start"
  systemctl status nginx --no-pager
  exit 1
fi

# Test NGINX can reach containers
echo "Testing NGINX connectivity to containers..."
sleep 5

# Test health endpoint through NGINX
curl -f http://localhost/ > /dev/null 2>&1 && echo "✓ NGINX health check working" || echo "⚠ NGINX health check failed"

# Cleanup unused images
docker image prune -a -f || true

echo "=== User Data Script Completed ==="
echo "Timestamp: $(date)"
echo ""
echo "Summary:"
echo "- NGINX installed and configured"
echo "- 5 users containers deployed"
echo "- NGINX routing configured"
echo "- All services accessible via ALB on port 80"
echo ""
echo "Final container status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
